apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: 'test-group'
  annotations:
    github.com/project-slug: serhii-butko/test-catalog/
spec:
  type: development
  profile:
    displayName: 'Test Group'
  children: []
  members: ['s.butko']
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: 's.butko'
  annotations:
    github.com/project-slug: serhii-butko/test-catalog/
spec:
  profile:
    displayName: 'Serhii Butko'
    email: 's.butko@itransition.com'
  memberOf: ['group:test-group']
